### ISSUE TITLE
Allow users to choose between left joystick and left "d-pad"

### ISSUE THREAD

**Issue by OrGoN3** [theflippedbit/opentyrian-nx#6]
That joystick was pretty darn sensitive, even though you already made it easier, lol.

**Comment by theflippedbit** [comment]
I don't think I changed the joystick sensitivity, not on purpose anyway! :D First release was just getting it to compile..

**Comment by OrGoN3** [comment]
I hope you didn't mind me compiling and releasing for 9.x.x. I am not trying to step on any toes, I just wanted a playable version on 9.x.x so I compiled with latest libnx. If I can help, please let me know!! ^_^

**Comment by theflippedbit** [comment]
No worries.. all good!

**Comment by theflippedbit** [comment]
Fixed with better defaults in #5
